### ISSUE TITLE
 Missing or badly formatted authorization token

### ISSUE THREAD

**Issue by Shrikant1212** [marinosoftware/DeviceCheckSample#4]
Hi there, I'm tired of getting this.I use your code and  upload in Heroku  and using development Apple URL can you help me in this 
Thanks for your time.

**Comment by timcolla** [comment]
Duplicate of #3 

I haven't had time to work on this since, and have no time to look at this now. But using Apple's production server seemed to work for me. Give that a go.

**Comment by Shrikant1212** [comment]
Now its working for me 
Thanks for your time.
And sorry for trouble.
